# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: City Car Park
email: cs@citycarpark.my
cs_email: cs@citycarpark.my
cs_phone: +603 4162 8672
description: > # this means to ignore newlines until "baseurl:"
  Citycarpark is a Parking Solution for all the parking problems in Kuala Lumpur.
# permalink: /:title
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dbkl.citycarpark.my" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: citycarpark
github_username:  citycarpark
google_analytics: UA-100178704-1

# Multi languages support
languages: [ "ms", "en" ]
# languages: ["en", "ms"]
exclude_from_localizations: [ "assets" ]

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
